name = "DelayNetTools"
uuid = "93871cbd-c3a7-4cb2-995f-072fee371c41"
authors = ["analogouscircuit <david.dahlbom@gmail.com> and contributors"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
GLMakie = "0.2"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
